# These are supported funding model platforms

github: [GitGuardApp] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
open_collective: GitGuardApp # Replace with a single Open Collective username
custom: https://buymeacoffee.com/GitGuard # Replace with a single custom sponsorship URL